name: Update Zurich data

on:
  schedule:
    - cron:  '0 7-9 * * *'

jobs:
  update_data:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup R and its depedencies
    - uses: r-lib/actions/setup-r@main
    - name: Install R dependencies
      run: |
        install.packages("tidyverse")
        install.packages("lubridate")
        install.packages("magrittr")
      shell: Rscript {0}
      
    # Prepare data
    - name: Prepare data with compute-StationDailyTimeSeries-GitHubAction.R
      run: Rscript dataProcessing/zurich/compute-StationDailyTimeSeries-GitHubAction.R

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update time-series data and reference data for Zurich, Switzerland
        branch: ${{ github.head_ref }}
