name: Update Germany data

on:
  schedule:
  - cron:  '0 0/6 * * *'

env:
  HYSTREET_API_KEY: ${{ secrets.HYSTREET_API_KEY }}
  
jobs:
  update_data:
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup R and its depedencies
    - uses: r-lib/actions/setup-r@main
    - name: Install R dependencies
      run: |
        install.packages("tidyverse")
        install.packages("lubridate")
        install.packages("magrittr")
        install.packages("hystReet")
      shell: Rscript {0}
      
    # Prepare data
    - name: Prepare data with compute-StationDailyTimeSeries-GitHubAction.R
      run: Rscript dataProcessing/germany/compute-StationDailyTimeSeries-GitHubAction.R

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update time-series data, reference data and location data for Germany
        branch: ${{ github.head_ref }}
